    const ratingContainerVarients = {
        hidden:{
        y:100,
        opacity:0,
        },
        visible:{
        y:0,
        opacity:1,
        transition:{
            duration:0.5,
            delay:1
        }
        }
    }
    const ratingNumberInfoContainerVarients = {
        visible:{
            height:360,
            transition:{
                duration:0.3,
                ease:"easeInOut"
            }
        }
    }
    const textVarients = {
        hidden:{
        x:20,
        opacity:0
        },
        visible:{
        x:0,
        opacity:1,
        transition:
        {
            duration:0.5
        }
        },
        leave:{
        x:-20,
        opacity:0,
        transition:{
            duration:0.5,
            delay:0.5
        }
        }
    } 
    const IngredientsVarients = {
        visible:{
            height:150,
            x:0,
            opacity:1,
            transition:{
                duration:0.3,
                ease:"easeInOut"
            }
        },
        leave:{
            x:-20,
            opacity:0,
            transition:{
                duration:0.5,
                delay:0.5
            }
        }
    }
    const ratingNumberVarients = {
        hidden:{
        rotateX:"90deg",
        y:"15px",
        scale:0.8,
        transformOrigin:"bottom center"
        },
        visible:{
        rotateX:0,
        y:0,
        scale:1,
        transition:{
            duration:0.5
        }
        },
        leave:{
        rotateX:"-90deg",
        y:0,
        scale:0.8,
        transformOrigin:"top center",
        transition:{
            delay:0.5,
            duration:0.5
        }
        }
    }
    const usersRatesVarients = {
        onHover:{
        width:125,
        borderRadius:"25px",
        justifyContent:"start",
        padding:"10px",
        transition:{
            ease:"easeIn"
        }
        },
        hidden:{
            opacity:0,
            x:20
        },
        visible:{
            opacity:1,
            x:0
        }
    }

export {ratingContainerVarients,textVarients,ratingNumberVarients,usersRatesVarients,IngredientsVarients,ratingNumberInfoContainerVarients}